trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals MONITH

variables:
  angularProject: 'placement-portal-frontend'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- script: |
    npm install
  displayName: 'Install node_modules'

- script: |
    npx ng build --configuration production
  displayName: 'Build Angular App'

- script: |
    npx ng test --watch=false --code-coverage --browsers=ChromeHeadless
  displayName: 'Run Angular Unit Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: 'test-results/test-results.xml'
    testRunTitle: 'Angular Unit Tests'

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'coverage/$(angularProject)/cobertura-coverage.xml'
    reportDirectory: 'coverage/$(angularProject)'
    failIfCoverageEmpty: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/$(angularProject)'
    ArtifactName: 'angular-dist'
    publishLocation: 'Container'
  displayName: 'Publish Angular Build Output'

- task: PublishBuildArtifacts@1
  condition: always()  # ✅ Add this line to force artifact publish
  inputs:
    PathtoPublish: 'coverage/$(angularProject)'
    ArtifactName: 'test-report-html'
    publishLocation: 'Container'
  displayName: 'Publish HTML Coverage Report'
