trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals MONITH

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- script: |
    npm install
  displayName: 'Install node_modules'

- script: |
    npx ng build --configuration production
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'angular-dist'
    publishLocation: 'Container'
