trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals MONITH

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

- script: |
    ng build --configuration production
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'angular-dist'
    publishLocation: 'Container'
